const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
    _id: String,
    prefix: { type: String, default: `.` },
    users: { type: Object, default: {} },
    staffRoles: { type: Array, default: [] },
    tickets: { type: Array, default: [] },
    ticketPanels: { type: Object, default: {} },
    ticketLogs: { type: String, default: `` },
    suggestions: { type: Object, default: {} },
    suggestionChannel: { type: String, default: `` },
    modLogs: { type: String, default: `` },
    discordLogs: { type: String, default: `` },
    levels: { type: Object, default: {} },
    ticketNumber: { type: Number, default: 1 },
    requestRoles: { type: Object, default: {} },
    requestedRoles: { type: Object, default: {} },
    requestRolelogs: { type: String, default: `` },
    caseNumber: { type: Number, default: 1 },
    cases: { type: Object, default: {} },
    muteCases: { type: Object, default: {} },
    muteRole: { type: String, default: `` },
    welcomes: { type: String, default: `` },
    welcomeLogs: { type: String, default: `` },
    autoRole: { type: String, default: `` },
    appLogs: { type: Object, default: {} },
    applications: { type: Object, default: {} },
    applicants: { type: Object, default: {} },
    managers: { type: Array, default: [] },
    fiveMDisplay: { type: String, default: `` },
    port: { type: String, default: `` },
    ip: { type: String, default: `` },
    stickies: { type: Object, default: {} },
    levels: { type: Object, default: {} },
    strikeNumber: { type: Number, default: 1 },
    strikes: { type: Object, default: {} },
    strikePermissions: { type: Array, default: [] },
    strikeLogs: { type: String, default: `` },
    suggestionChannel: { type: String, default: `` },
    suggestions: { type: Object, default: {} },
    discordCount: { type: String, default: `` },
    reactionRoles: { type: Object, default: {} },
    dmSupport: { type: Object, default: "" },
    dmSupportCategory: { type: String, defatul: "" },
    supportVoiceChannel: { type: String, default: "" },
    supportChannels: { type: Array, default: [] },
    supportRoles: { type: Array, default: [] },
    reactionRoles: { type: Object, default: {} },
    ticketCategory: { type: String, default: "" },
    twitchRole: { type: String, default: "" },
    twitchKeyWords: { type: Array, default: [] }
});
module.exports = mongoose.model(`data`, productSchema);